language: node_js
node_js:
  - "6"

after_success:
  - npm run coverage
  - npm run coveralls
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info

after_failure:
  - npm run coverage
  - npm run coveralls